[package]
name = "ethkeysgx" # Note: changes here need mirroring in Makefile
version = "0.1.0"
authors = ["gregkapka <greg@oraclize.it>"]
build = "build.rs"

[dependencies]
docopt = "1.0.1"
secp256k1_enclave_rust = { path = "../" }