[package]
name = "sgx-enclave-ec-keygen" # Note: changes here need mirroring in Makefile
version = "0.1.0"
authors = ["gregkapka <greg@oraclize.it>"]
build = "build.rs"

[dependencies]
secp256k1_enclave_rust = { path = "../" }